backend/backend/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers

import todo.views
from todo import views


router = routers.DefaultRouter()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('todo.urls')),
]

crackmes/urls.py
from django.urls import path
from .views import *

app_name = 'crackmes'

urlpatterns = [
    path('submit/', submit_crackme, name='submit_crackme'),
    path('download/<int:pk>/', download_binary, name='download_binary'),
    path('<str:username>/', crackme_list_for_user, name='crackme_list_for_user'),
    path('<str:username>/<str:title>/', crackme_detail, name='crackme_detail'),
    path('<str:username>/<str:title>/download/', download_binary, name='download_binary'),
    path('<str:username>/<str:title>/submit_solution/', submit_solution, name='submit_solution'),
    path('<str:username>/<str:title>/download_solution/', download_solution, name='download_solution'),
    path('', CrackmeListView.as_view(), name='crackme_list'),

]

main/urls.py
# main/urls.py

from django.urls import path
from .views import *

urlpatterns = [
    path('', home, name='home'),
    path('logout/', user_logout, name='logout'),
]

reverse/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chat.urls')),
    path('', include('authentication.urls')),
    path('', include('main.urls')),
    path('crackmes/', include('crackmes.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crackmes/models.py
# models.py

from django.utils import timezone
from django.db import models
from django.contrib.auth.models import User

def custom_upload_to(instance, filename):
    # Get the username and title
    username = instance.user.username
    title = instance.title

    # Construct the file path
    file_path = f'crackme_binaries/{username}_{title}_{filename}'
    return file_path

class Crackme(models.Model):
    OPERATING_SYSTEM_CHOICES = [
        ('Windows', 'Windows'),
        ('Linux', 'Linux'),
        ('MacOS', 'MacOS'),
        ('Other', 'Other'),
    ]

    title = models.CharField(max_length=255)
    description = models.TextField()
    operating_system = models.CharField(max_length=20, choices=OPERATING_SYSTEM_CHOICES)
    hardness_level = models.IntegerField(choices=[(i, str(i)) for i in range(1, 6)], default=1)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    binary_file = models.FileField(upload_to=custom_upload_to, null=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user', 'title'], name='unique_user_title')
        ]

    def __str__(self):
        return f"{self.title} by {self.user.username}" 

class Solution(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    crackme = models.ForeignKey(Crackme, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    description = models.TextField()
    binary_file = models.FileField(upload_to='solution_binaries/', null=True)

    def __str__(self):
        return f'{self.user.username} - {self.title}'

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    crackme = models.ForeignKey(Crackme, on_delete=models.CASCADE)
    text = models.TextField()
    timestamp = models.DateTimeField()

    def save(self, *args, **kwargs):
        if not self.timestamp:
            self.timestamp = timezone.now()
        return super().save(*args, **kwargs)
    
    def __str__(self):
        return f'{self.user.username} - {self.crackme.title}'

crackmes/forms.py
# forms.py
from django import forms
from .models import Crackme, Comment, Solution

class CrackmeSubmissionForm(forms.ModelForm):
    class Meta:
        model = Crackme
        fields = ['title', 'description', 'operating_system', 'hardness_level', 'binary_file']

    def clean_title(self):
        title = self.cleaned_data['title']
        user = self.cleaned_data.get('user')

        if user and Crackme.objects.filter(user=user, title=title).exists():
            raise forms.ValidationError("A Crackme with this title already exists for the user.")
        return title


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.fields['text'].widget = forms.Textarea(attrs={'rows': 3, 'placeholder': 'Enter your comment here...'})

class SolutionForm(forms.ModelForm):
    class Meta:
        model = Solution
        fields = ['title', 'description', 'binary_file']

crackmes/views.py
# crackmes/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.views import View
from .forms import CrackmeSubmissionForm, CommentForm, SolutionForm
from .models import Crackme, Comment, Solution
from django.contrib.auth.models import User
from django.http import FileResponse, HttpResponse
from django.shortcuts import get_object_or_404

@login_required
def submit_crackme(request):
    if request.method == 'POST':
        form = CrackmeSubmissionForm(request.POST, request.FILES)
        if form.is_valid():
            crackme = form.save(commit=False)
            crackme.user = request.user

            # Check if a Crackme with the same title already exists for the user
            existing_crackme = Crackme.objects.filter(user=crackme.user, title=crackme.title).first()
            if existing_crackme:
                # Handle the case where a Crackme with the same title already exists
                # You can redirect to an error page, show a message, etc.
                return HttpResponse("A Crackme with this title already exists for the user.")

            crackme.save()
            return redirect('/')
    else:
        form = CrackmeSubmissionForm()

    return render(request, 'submit_crackme.html', {'form': form})

def crackme_list_for_user(request, username):
    user = User.objects.get(username=username)
    crackmes = Crackme.objects.filter(user=user)
    return render(request, 'crackme_list_for_user.html', {'crackmes': crackmes, 'user': user})

def crackme_detail(request, username, title):
    user = request.user  # This assumes you have the authentication middleware enabled
    crackme = get_object_or_404(Crackme, user__username=username, title=title)
    comments = Comment.objects.filter(crackme=crackme)
    solutions = Solution.objects.filter(crackme=crackme)
    if request.method == 'POST' and user.is_authenticated:
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.user = user
            comment.crackme = crackme
            comment.save()
    else:
        comment_form = CommentForm()

    return render(request, 'crackme_detail.html', {'crackme': crackme, 'user': user, 'comments': comments, 'comment_form': comment_form, "solutions": solutions})

def download_binary(request, pk):
    crackme = get_object_or_404(Crackme, pk=pk)
    file_path = crackme.binary_file.path
    return FileResponse(open(file_path, 'rb'), content_type='application/octet-stream')

def download_binary(request, username, title):
    crackme = get_object_or_404(Crackme, user__username=username, title=title)

    if crackme.binary_file:
        response = FileResponse(crackme.binary_file)
        original_filename = crackme.binary_file.name.split('/')[-1]
        response['Content-Disposition'] = f'attachment; filename="{original_filename}"'
        return response
    else:
        # Handle the case where there is no binary file available
        # You can redirect to an error page or show a message
        return HttpResponse("No binary file available for download.")
    
def submit_solution(request, username, title):
    user = request.user
    crackme = get_object_or_404(Crackme, user__username=username, title=title)

    if request.method == 'POST' and user.is_authenticated:
        solution_form = SolutionForm(request.POST, request.FILES)
        if solution_form.is_valid():
            solution = solution_form.save(commit=False)
            solution.user = user
            solution.crackme = crackme
            solution.save()
            return redirect('crackmes:crackme_detail', username=username, title=title)
    else:
        solution_form = SolutionForm()

    return render(request, 'submit_solution.html', {'crackme': crackme, 'user': user, 'solution_form': solution_form})

def download_solution(request, username, title):
    solution = get_object_or_404(Solution, user__username=username, title=title)
    # Assuming 'binary_file' is the FileField in your Solution model
    response = FileResponse(solution.binary_file, content_type='application/force-download')
    response['Content-Disposition'] = f'attachment; filename="{solution.binary_file.name}"'
    return response

class CrackmeListView(View):
    template_name = 'crackme_list.html'  # Create this template

    def get(self, request):
        crackmes = Crackme.objects.all()
        context = {'crackmes': crackmes}
        return render(request, self.template_name, context)

crackmes/templates/base.html
<!-- templates/base.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}My Django Project{% endblock %}</title>
</head>
<body>

    <header>
        <h1>{% block header %}My Django Project{% endblock %}</h1>
        <!-- Add navigation or other header content here -->
    </header>

    <main>
        {% block content %}{% endblock %}
    </main>

    <footer>
        <!-- Add footer content or links here -->
    </footer>


</body>
</html>

crackmes/templates/crackme_detail.html
<!-- crackmes/templates/crackme_detail.html -->
<h2>{{ user.username }} - {{ crackme.title }}</h2>
<p>Description: {{ crackme.description }}</p>
{% if crackme.binary_file %}
    <a href="download">Download Binary</a>
{% else %}
    <p>No binary file available for download.</p>
{% endif %}

<h3>Solutions:</h3>
<ul>
    {% for solution in solutions %}
        <li><a href="{% url 'crackmes:download_solution' username=solution.user.username title=solution.title %}">{{ solution.user.username }} - {{ solution.title }}</a></li>
    {% endfor %}
</ul>

{% if user.is_authenticated %}
    <h3><a href="{% url 'crackmes:submit_solution' username=crackme.user.username title=crackme.title %}" target="_blank">Submit Solution</a></h3>
{% else %}
    <p><a href="/login">Login</a> to comment.</p>
{% endif %}

<h3>Comments:</h3>
<ul>
    {% for comment in comments %}
        <li>{{ comment.user.username }} ({{ comment.timestamp|date:"F d, Y H:i:s" }}): {{ comment.text }}</li>
    {% endfor %}
</ul>

{% if user.is_authenticated %}
    <h3>Add a Comment:</h3>
    <form method="post" action="{% url 'crackmes:crackme_detail' username=crackme.user.username title=crackme.title %}">
        {% csrf_token %}
        {{ comment_form.text }}
        <button type="submit">Post Comment</button>
    </form>
{% else %}
    <p><a href="/login">Login</a> to comment.</p>
{% endif %} 

crackmes/templates/crackme_list.html
<h2>Crackme List</h2>

<ul>
    {% for crackme in crackmes %}
        <li><a href="{% url 'crackmes:crackme_detail' username=crackme.user.username title=crackme.title %}">{{ crackme.title }}</a></li>
    {% endfor %}
</ul>

crackmes/templates/crackme_list_for_user.html
<h2>Crackmes for {{ user.username }}</h2>
<ul>
    {% for crackme in crackmes %}
        <li><a href="{{crackme.title}}">{{ crackme.title }}</a></li>
    {% endfor %}
</ul>

crackmes/templates/submit_crackme.html
<!-- crackme/templates/crackme/submit_crackme.html -->
{% extends 'base.html' %}

{% block content %}
  <h2>Submit a New Crackme</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
  </form>
{% endblock %}

crackmes/templates/submit_solution.html
<!-- submit_solution.html -->
<h2>Submit Solution for {{ crackme.title }}</h2>
<form method="post" action="{% url 'crackmes:submit_solution' username=crackme.user.username title=crackme.title %}" enctype="multipart/form-data">
    {% csrf_token %}
    {{ solution_form.as_p }}
    <button type="submit">Submit Solution</button>
</form>